version: "3.8"

services:
  db:
    image: postgres:15
    container_name: messenger_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: messenger
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
